name: Generate Profile Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # daily refresh
  workflow_dispatch:        # lets you trigger it manually anytime
  push:
    branches: [ main ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: harsha5200-d
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
